import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MapBackground from "./[map]/MapBackground";
import AuthProvider from "./components/auth/AuthProvider";
import { MapProvider } from "./context/MapContext";
import "./globals.css";

import type { Viewport } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vivu App",
  description: "Generated by taimeooo",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <MapProvider>
            <MapBackground />
            {children}
          </MapProvider>
          <ToastContainer position="bottom-right" theme="colored" />
        </AuthProvider>
      </body>
    </html>
  );
}
